# Generated by Django 3.2.6 on 2024-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20240211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='distributeur_pains',
        ),
        migrations.AlterField(
            model_name='contact',
            name='types_de_machines',
            field=models.CharField(choices=[('autres', 'Autres'), ('casiers', 'Casiers'), ('circuits_courts', 'Circuits courts'), ('distributeur_pains', 'Distributeur pains'), ('distributeur_epicerie', 'Distributeur épicerie'), ('distributeur_boisson_snacking', 'Distributeur boisson et snacking'), ('distributeur_traiteur', 'Distributeur traiteur'), ('distributeur_cbd', 'Distributeur CBD'), ('distributeur_charcuterie', 'Distributeur charcuterie'), ('distributeur_salle_sport', 'Distributeur Salle Sport'), ('distributeur_viandes', 'Distributeur Viandes'), ('distributeur_fromages', 'Distributeur Fromages'), ('distributeur_non_alimentaire', 'Distributeur non alimentaire'), ('frigo_connecte', 'Frigo connecté')], default='autres', max_length=50),
        ),
    ]
